name: Deploy to DEV
on: 
  push:  
    branches:
      - main
jobs: 
  Deploy:
    name: Deploy to DEV
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code 
        uses: actions/checkout@v3
       
      - name: Deploy to DEV
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_KEY_DEV }}
          REMOTE_HOST: ${{ secrets.HOST_NAME_DEV }}
          REMOTE_USER: ${{ secrets.USERNAME_DEV }}
       

      - name: Set up SSH key
        run: |
         mkdir -p ~/.ssh
         echo "${{ secrets.SSH_KEY_DEV }}" > ~/.ssh/id_rsa
         chmod 600 ~/.ssh/id_rsa
         # Add the SSH key to the known_hosts file (replace hostname with your actual hostname)
         ssh-keyscan -H ${{ secrets.HOST_NAME_DEV}} >> ~/.ssh/known_hosts
         sudo apt-get install sshpass

      - name: Deploy to server
        run: |
          sshpass -p '${{ secrets.SSH_KEY_DEV }}' ssh -v -o StrictHostKeyChecking=no ${{ secrets.USERNAME_DEV }}@${{ secrets.HOST_NAME_DEV }} <<'ENDSSH'
          cd ${{ secrets.TARGET_DEV_DIR }}
          ./deploy.sh
          ENDSSH
